AWSTemplateFormatVersion: "2010-09-09"

Description: "Create 2 volumes unattached to using in Custodian examples"

Parameters:

  ResourceName:
    Type: String
    Description: "Name that will be using in disks and topic"
    Default: FinOps-C7N-EBS-Example

  DiskSize:
    Type: String
    Description: "Size of disks"
    Default: 1

  Email2Notify:
    Type: String
    Description: "Email to notify"

Resources:

  DiskOneExample:
    Type: AWS::EC2::Volume
    Properties: 
      AvailabilityZone: us-east-1a
      Size: !Ref DiskSize
      Tags: 
        - Key: Name
          Value: !Join
            - '-'
            - - !Ref ResourceName
              - 'DiskOne'
      VolumeType: gp2

  DiskTwoExample:
    Type: AWS::EC2::Volume
    Properties: 
      AvailabilityZone: us-east-1a
      Size: !Ref DiskSize
      Tags: 
        - Key: Name
          Value: !Join
            - '-'
            - - !Ref ResourceName
              - 'DiskTwo'
      VolumeType: gp2

  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: !Ref ResourceName
      Subscription: 
        - Endpoint: !Ref Email2Notify
          Protocol: email
      TopicName: !Ref ResourceName
