AWSTemplateFormatVersion: "2010-09-09"

Description: "Create 1 Redshift Instance and 1 SNS to using in Custodian examples"

Parameters:

  ResourceName:
    Type: String
    Description: "Name that will be using in resources"
    Default: FinOps-C7N-Underutilized-Amazon-Redshift-Clusters

  Email2Notify:
    Type: String
    Description: "Email to notify"

  SubnetID:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "Your Subnets"

Resources:

  RedShiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterIdentifier: !Ref ResourceName
      ClusterType: single-node
      DBName: finopsc7ndbname
      MasterUsername: finopsc7ndbuser
      MasterUserPassword: Finopsc7ndbpass
      NodeType: dc2.large
      ClusterSubnetGroupName: !Ref RedShiftClusterSubnetGroup

  RedShiftClusterSubnetGroup:
    Type: 'AWS::Redshift::ClusterSubnetGroup'
    Properties:
      Description: "SubnetGroup created to testing C7N policies"
      SubnetIds: !Ref SubnetID

  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: !Ref ResourceName
      Subscription: 
        - Endpoint: !Ref Email2Notify
          Protocol: email
      TopicName: !Ref ResourceName

Outputs:

  NotificationARN:
    Description: SNS ARN to use in your C7N policy
    Value: !Ref NotificationTopic